### ISSUE TITLE
in catalog-get-tokenuri transformation filter for zora metadata with prop `version: "catalog-..."` to only retrieve music NFTs

### ISSUE THREAD

**Issue by TimDaub** [neume-network/strategies#125]

**Comment by il3ven** [comment]
Doesn't this issue conflict with #105? This issue asks to add filter to existing catalog-get-tokenuri where as #105 asks to create a new strategy to filter NFTs with `version: "catalog-...`.

Also, how do you know that all music NFTs on Zora will contain `version: "catalog-...`?

**Comment by TimDaub** [comment]
> Also, how do you know that all music NFTs on Zora will contain `version: "catalog-...`?

We're only interested in music files on Zora from catalog, hence we only want version: "catalog".

> Doesn't this issue conflict with #105? This issue asks to add filter to existing catalog-get-tokenuri where as #105 asks to create a new strategy to filter NFTs with `version: "catalog-...`.

Yes #105 and #125 are duplicates.
