### ISSUE TITLE
soundxyz-metadata transformer is being called multiple times

### ISSUE THREAD

**Issue by il3ven** [neume-network/strategies#154]
There is a bug in the current implementation. The soundxyz-metadata transformer is being called multiple times.

Have a look at [soundxyz-metadata-extraction](https://github.com/TimDaub/temp-neume-data-dir-results/blob/01af45b37bbd51652ed8bc615a2b08c8c3bc0ed5/soundxyz-metadata-extraction) file. It has 25 lines which is correct according to the current logic. There are 25 NFTs in web3subgraph with the address 0x01ab7d30525e4f3010af27a003180463a6c811a6.

Have a look at [soundxyz-metadata-transformation](https://github.com/TimDaub/temp-neume-data-dir-results/blob/01af45b37bbd51652ed8bc615a2b08c8c3bc0ed5/soundxyz-metadata-transformation). It has 369 lines. soundxyz-metadata-transformation should contain the same number of lines as soundxyz-metadata-extraction.

#### Cause

This message should only be posted for the last message.

https://github.com/neume-network/strategies/blob/d424b17581287b3b3c422957195a073fd4744c3f/src/strategies/soundxyz-metadata/extractor.mjs#L100-L109

**Comment by TimDaub** [comment]
ah damn, I was already wondering. Then maybe this is making the crawl to take ages at neume-network/data. I'll try to remove it and report back! Thanks for reporting your finding!

**Comment by TimDaub** [comment]
would a solution of this problem if we did one eth_call per strategy (e.g. separate strategies for "editions" and "tokenToEditions"?

Would a multicall utility help? https://github.com/rugpullindex/eth-fun/issues/40

**Comment by il3ven** [comment]
> would a solution of this problem if we did one eth_call per strategy (e.g. separate strategies for "editions" and "tokenToEditions"?

That would also be a solution.

Another solution I had in mind was to unmount the strategy when `number_of_posted_messages === number_of_consumed_messages`. The lifecycle handler can keep track of this number. We are doing this sort of thing in snapshot test utility.

https://github.com/neume-network/strategies/blob/16f91e5288ddcd05aa85f97977c0be62b5bb1f46/utils/snapshot_extractor.mjs#L44-L46

**Comment by TimDaub** [comment]
mhh not sure if this generally would work out as upon unmount, a strategy post new messages, no?

**Comment by il3ven** [comment]
for most cases i think it should work. it is working in snapshot_extractor. we can also look into better queue maintaining order.

**Comment by TimDaub** [comment]
I suggest u propose this in a PR and we review it then specifically
