### ISSUE TITLE
global request timeout should be configurable via env variable from neume-network/core

### ISSUE THREAD

**Issue by TimDaub** [neume-network/strategies#157]
- timeout is currently hardcoded: https://github.com/neume-network/strategies/blob/d718673e0c390e82d0a38f0e9911d4e6bf2935b0/src/lifecycle.mjs#L31
- but it should be a configuration option like other environment variables set in neume-network/core

**Comment by il3ven** [comment]
Closing this issue since there is no longer a global timeout. Strategies can set timeout per message or set a global timeout per endpoint in `config.mjs`. Feel free to reopen.

**Comment by TimDaub** [comment]
great, thank you!
