### ISSUE TITLE
The transformation strategy interface doesn't allow inputs 

### ISSUE THREAD

**Issue by TimDaub** [neume-network/strategies#177]
- E.g. say after "call-block-logs", we wanted to filter all logs with a specific type of event, we can't because a transformer strategy doesn't accept any custom inputs we can set as users.
- See interface definition: https://github.com/neume-network/strategies#transformer-strategy-interface-definition
- This is also reflected in message-schema. lifecycleMessage.args as it can be nulled: https://github.com/neume-network/message-schema/blob/a66dbf12a37709177aa238b2c8e08ec105a90097/src/index.mjs#L160
- E.g. it'd be great if we could pass in the events/addresses we wanted to filter for: https://github.com/neume-network/strategies/blob/54ca4226b8346dc4ede14042427c1c8826a72950/src/strategies/call-block-logs/transformer.mjs#L25 https://github.com/neume-network/strategies/blob/54ca4226b8346dc4ede14042427c1c8826a72950/src/strategies/call-block-logs/transformer.mjs#L45

**Comment by il3ven** [comment]
According to what I understood from the requirements. The following interface should work.

```ts
interface Transformer {
  name: String;
  onLine(line: String, args...): Object<messages:  Message[], write: String>;
  onError(error: Error): any;
  onClose(): Object<messages:  Message[], write: String>;
}
```

```js
const crawlPath = {
  [
    {
      name: "call-block-logs",
      extractor: {},
      transformer: {
        args: ["./fileToReadFrom", arg1, arg2],
      },
    },
  ],
}
```

In function `onLine` the first argument `line` will be a line from `fileToReadFrom` and second argument will be `arg1` and the third argument will be `arg2`.

If we are feeling ambitious we can even remove `onClose`. I don't think it serves any purpose right now.

@TimDaub What do you say? I am 100% open for changes to my proposed interface.

**Comment by TimDaub** [comment]
> In function `onLine` the first argument `line` will be a line from `fileToReadFrom` and second argument will be `arg1` and the third argument will be `arg2`.

OK, I think this is a good solution!

> If we are feeling ambitious we can even remove `onClose`. I don't think it serves any purpose right now.

out of scope of this issue but I'm not disagreeing haha
