### ISSUE TITLE
call-block-logs snapshot test fails locally

### ISSUE THREAD

**Issue by il3ven** [neume-network/strategies#182]
The [call-block-logs snapshot test](https://github.com/neume-network/strategies/blob/6d2081abf2daeb1812f0568449c51816c7c76cfc/src/strategies/call-block-logs/extractor.mjs#L1-L2) fails locally but passes in the pipeline. For me this is the error.

```
Uncaught exception in test/strategies/call-block-logs/extractor_test.mjs

Error: RPCError: Encountered error when trying to parse JSON body result: "<html>
<head><title>401 Authorization Required</title></head>
<body>
<center><h1>401 Authorization Required</h1></center>
<hr><center>nginx/1.18.0 (Ubuntu)</center>
</body>
</html>
", error: "SyntaxError: Unexpected token < in JSON at position 0"

› ", error: "SyntaxError: Unexpected token < in JSON at position 0"
› Worker.<anonymous> (file://utils/snapshot_extractor.mjs:33:13)
```

I have verified that my `RPC_API_KEY` is valid. My first guess is that call-block-logs/extractor is missing the following line.

```
if (env.RPC_API_KEY) {
  options.headers = {
    Authorization: `Bearer ${env.RPC_API_KEY}`,
  };
}
```

**Comment by TimDaub** [comment]
> I have verified that my `RPC_API_KEY` is valid. My first guess is that call-block-logs/extractor is missing the following line.

sounds reasonable. I also think adding the line should fix it.

**Comment by il3ven** [comment]
Somewhat unrelated but how is the pipeline at neume-network/data working without [RPC_API_KEY](https://github.com/neume-network/data/blob/main/.github/workflows/node.js.yml#L38)?

**Comment by TimDaub** [comment]
> Somewhat unrelated but how is the pipeline at neume-network/data working without [RPC_API_KEY](https://github.com/neume-network/data/blob/main/.github/workflows/node.js.yml#L38)?

I think neume-network/data never calls call-block-logs

**Comment by il3ven** [comment]
> I think neume-network/data never calls call-block-logs

Yes, it doesn't but calls to RPC_HTTP_HOST do happen. Are we using a free ethereum node there?

**Comment by TimDaub** [comment]
> Are we using a free ethereum node there?

I'm not sure as I can't see the env variables on GitHub anymore. But I believe that on GitHub Actions we're using a link to an alchemy.com API path, which means the authorization key is actually included in the URI and hence it doesn't matter if the `Authorization` header is defined or not.
