### ISSUE TITLE
Lifecycle isn't properly validating message formats at runtime

### ISSUE THREAD

**Issue by TimDaub** [neume-network/strategies#187]
- https://github.com/neume-network/strategies/blob/main/src/lifecycle.mjs relies on well-formatted message formats in many places of the implementation
- But it also never checks the JSON schema https://github.com/neume-network/message-schema/blob/main/src/index.mjs that it relies upon
- Here are some places where neume-network/strategies should not trust but better verify:
  - https://github.com/neume-network/strategies/blob/3aace67a997a53101af0df7b8bf7ae2d141fe6e6/src/lifecycle.mjs#L43
  - https://github.com/neume-network/strategies/blob/3aace67a997a53101af0df7b8bf7ae2d141fe6e6/src/lifecycle.mjs#L48
  - https://github.com/neume-network/strategies/blob/3aace67a997a53101af0df7b8bf7ae2d141fe6e6/src/lifecycle.mjs#L53
  - https://github.com/neume-network/strategies/blob/3aace67a997a53101af0df7b8bf7ae2d141fe6e6/src/lifecycle.mjs#L131
  - https://github.com/neume-network/strategies/blob/3aace67a997a53101af0df7b8bf7ae2d141fe6e6/src/lifecycle.mjs#L183

**Comment by il3ven** [comment]
Is the current crawlPathMessage okay? Should I formally define it in neume-network/schema?

https://github.com/neume-network/core/blob/main/crawl_path.mjs#L12-L17

**Comment by TimDaub** [comment]
> Should I formally define it in neume-network/schema?

yes

> Is the current crawlPathMessage okay?

yes

**Comment by il3ven** [comment]
@TimDaub I was adding runtime checks for proper schemas. I can see a problem. Since these checks are at runtime and for every message posted to worker. They can slow down our application when working at scale. Unlike TypeScript these checks won't happen at build time but at runtime for every message.

Should we trust the strategy?

**Comment by TimDaub** [comment]
> are at runtime

that's good. We want to validate values and not types.

> They can slow down our application when working at scale.

That's fine, we can address slow down when it becomes a problem. But correctness ultimately must have a higher priority than speed.

> Unlike TypeScript these checks won't happen at build time but at runtime for every message.

I don't see the usefulness of Typescript checks anywhere but in, e.g., the public interface definitions of a strategy module for automation of a strategy's integrity, E.g., as we've tried to do here: https://github.com/neume-network/strategies/pull/163. I

> Should we trust the strategy?

No. We must always JSON schema validate everything coming from a strategy, especially when we want many people to later commit strategies to this repository.

**Comment by il3ven** [comment]
Ok. I have created a PR (#204) for validating messages from strategies. I am removing [`lifecycleMessage`](https://github.com/neume-network/message-schema/blob/90ba9c19f99ecf489d76abf12299e492f7f98fd8/src/index.mjs#L144) from neume-network/message-schema as it is no longer used. Strategies now don't return `lifecycleMessage`. Instead we now have `crawlPath`. The schema for it I think should be defined in neume-network/schema as it is not internal.
