### ISSUE TITLE
something continuously kills lifecycle of long-running strategy

### ISSUE THREAD

**Issue by TimDaub** [neume-network/strategies#195]
- I've tried multiple times to run https://github.com/neume-network/strategies/blob/main/src/strategies/call-block-logs/extractor.mjs for extended periods (> 2h) and eventually the strategy is just shut down for now apparent reason
- no helpful related logs are emitted

```
2022-08-07T04:35:12.748Z neume-network-extraction-worker:worker Queue stats: {"successRate":0.9997004955950248,"peak":625472,"average":3487264.5626161993,"total":176959}
2022-08-07T04:35:12.749Z neume-network-extraction-worker:worker Queue stats: {"successRate":0.9997004972875226,"peak":625472,"average":3487291.886499774,"total":176960}
```

- All events to that point end up being written smoothly but beyond that, it's like the program shut down
- `ps ax | grep node` also shows no sign of a node process

**Comment by TimDaub** [comment]
potential fatal flaw: https://github.com/neume-network/strategies/blob/4c929075d8323d7449db7fa7b376d30aaf3dee4e/src/lifecycle.mjs#L129 doesn't await

**Comment by TimDaub** [comment]
> potential fatal flaw:
> 
> https://github.com/neume-network/strategies/blob/4c929075d8323d7449db7fa7b376d30aaf3dee4e/src/lifecycle.mjs#L129
> doesn't await

mhh after another thought about this. Not sure if this fixed anything. We don't use `update` as async: "async function update"

**Comment by TimDaub** [comment]
#196 sadly doesn't resolve this. It is the same pattern where the process runs for a relatively fixed amount of time and that just suddenly stops without any indication about what the problem may be

<img width="954" alt="Screenshot 2022-08-07 at 11 31 54" src="https://user-images.githubusercontent.com/2758453/183284564-d656d1bf-8d85-4739-ba12-725847a12e9b.png">

**Comment by TimDaub** [comment]
two other ideas to find the fault

1. switch out queue
2. roll back changes to old lifecycle function

in both cases, repeat running the call-block-logs extractor

**Comment by il3ven** [comment]
@TimDaub Try adding this log. At least it will tell us if there's a problem with the `extract` function and if messages are being lost.

https://github.com/neume-network/strategies/blob/629c1ef4560ecac2f9d294be3e65b86b7f818f4e/src/lifecycle.mjs#L102-L106

**Comment by il3ven** [comment]
Does the application stop or does it hang?

**Comment by TimDaub** [comment]
ps ax | grep node doesn't show a process anymore so it seems like it crashes but there are no logs

**Comment by TimDaub** [comment]
I've now reverted to 2424ebee5db960964ede0df7968b48a9005fc0e3 and @neume-network/extraction-worker@0.3.2 and I'm checking if the crawl also ends after a specific period of time. My thesis currently is that we're overwhelming better-queue, so if that instance suffers the same error as the latest main branch, we know it's better-queue and not a tricky race condition in the `function extract`

**Comment by TimDaub** [comment]
> I've now reverted to [2424ebe](https://github.com/neume-network/strategies/commit/2424ebee5db960964ede0df7968b48a9005fc0e3) and @neume-network/extraction-worker@0.3.2 and I'm checking if the crawl also ends after a specific period of time. My thesis currently is that we're overwhelming better-queue, so if that instance suffers the same error as the latest main branch, we know it's better-queue and not a tricky race condition in the `function extract`

OK, so I've now completed this run and it crashed predictably around the same duration mark again (about 2h)

<img width="954" alt="Screenshot 2022-08-07 at 17 57 22" src="https://user-images.githubusercontent.com/2758453/183299769-cd3d5535-d1c4-4ce8-a804-f2ae44341efd.png">


0xb39026 is the last block that was written

```
2022-08-07T15:54:36.108Z neume-network-extraction-worker:worker Queue stats: {"successRate":0.9999852092156447,"peak":434980,"average":3769109.6923516854,"total":202829}
2022-08-07T15:54:36.110Z neume-network-extraction-worker:worker Queue stats: {"successRate":0.9999852092885668,"peak":434980,"average":3769136.8036483754,"total":202830}
```

are the logs. So we can actually exclude the new implementation of extraction lifecycle being buggy and I rather think that something is off with the queue implementation we're using in the extraction-worker.

- https://github.com/neume-network/extraction-worker/issues/42
- https://github.com/neume-network/extraction-worker/issues/41

**Comment by il3ven** [comment]
At the end did using fastq fixed this issue?

**Comment by TimDaub** [comment]
I'm not sure. But I made an interesting observation: This always occurred when I started the process with nohup and & to pipe the output in a file and put the command in the background. It exclusively happened on servers where I connected to via SSH.

And it only happened when my computer went into sleep mode because of inactivity and the ssh connection broke. 

Have u seen this error anywhere else? I'm confident that the new lifecycle update works well (except potentially when the extraction worker doesn't report back messages e.g. in errors - but for that we should open a new issue)

**Comment by TimDaub** [comment]
https://github.com/neume-network/strategies/issues/203

**Comment by il3ven** [comment]
> Have u seen this error anywhere else?

No, I haven't. I'll keep an open eye in the future.
