### ISSUE TITLE
in case extraction worker loses messages, extract lifecycle may never exit strategy

### ISSUE THREAD

**Issue by TimDaub** [neume-network/strategies#203]

**Comment by TimDaub** [comment]
we could be observing this here: https://github.com/neume-network/data/issues/23

**Comment by il3ven** [comment]
I have looked at [fastq#drain](https://github.com/mcollina/fastq#drain). The approach to kill extractor when queue is empty will not work. First, it won't tell us when a single extractor strategy is done. It can only tell us when all the extractor strategies are done. Second, there can be a scenario when the queue is momentarily empty but new messages are incoming.

The other approach is to implement a timeout for each strategy which can be configured from the crawlPath. Let's suppose the timeout is 10 min. If no new message is received for 10min then we can kill the extractor strategy and warn the user of this forced kill.

**Comment by TimDaub** [comment]
@sirnicolaz should a strategy manually call exit itself or should we take care of it?

**Comment by TimDaub** [comment]
> have looked at [fastq#drain](https://github.com/mcollina/fastq#drain). The approach to kill extractor when queue is empty will not work. First, it won't tell us when a single extractor strategy is done. It can only tell us when all the extractor strategies are done. Second, there can be a scenario when the queue is momentarily empty but new messages are incoming.

I think this analysis is correct.

But I don't like the proposed solutions. We want something precise, correct and resilient. And e.g. assuming that the extractionworker will never lose messages has unfortunately not turned out to be realistic.

Here are paths forward:

- work more on extraction worker so that it guarantees that msgIn == msgOut
- work on strategies abstraction such that we allow the user to define termination conditions. E.g. what were the problems with the termination conditions? Could we slightly improve them?
- How do other similar programs handle this case? Do Research

**Comment by TimDaub** [comment]
I believe I will have fixed this in https://github.com/neume-network/strategies/commit/71e76b6b5ced756901b97f006ee34f6023b0341c

Using `async appendFile` generally lead to corrupted extractor files. In cases where we throw silent errors as here, we might lose track of the software's behavior: https://github.com/neume-network/strategies/blob/6f376fbc2c625fdd623fb747bb23451cb27d59a0/src/strategies/call-block-logs/transformer.mjs#L108

**Comment by il3ven** [comment]
> In cases where we throw silent errors as here, we might lose track of the software's behavior:

I agree on this part.

However, how does https://github.com/neume-network/strategies/commit/71e76b6b5ced756901b97f006ee34f6023b0341c fix this issue? What effect does `appendFileSync` have on extraction worker loosing messages?

**Comment by TimDaub** [comment]
> However, how does [71e76b6](https://github.com/neume-network/strategies/commit/71e76b6b5ced756901b97f006ee34f6023b0341c) fix this issue?

could be that it fixes it and that extraction worker never really lost messages...

**Comment by TimDaub** [comment]
let's close this issue and reopen it when we observe the bug again.
