### ISSUE TITLE
`function transform` isn't redirecting new messages to the worker

### ISSUE THREAD

**Issue by TimDaub** [neume-network/strategies#214]
- See this function: https://github.com/neume-network/strategies/blob/54ca4226b8346dc4ede14042427c1c8826a72950/src/lifecycle.mjs#L82
- In `lineReader` a buffer is created that tracks all messages emitted by a transformer: https://github.com/neume-network/strategies/blob/54ca4226b8346dc4ede14042427c1c8826a72950/src/lifecycle.mjs#L34
- And then this buffer is returned to `function transform`. But it never forwards those messages to the worker

**Comment by il3ven** [comment]
We can also look into changing the `transform` interface as to not return any messages. Earlier we were using it to start new strategies but currently they don't serve any purpose.

**Comment by TimDaub** [comment]
you are right it sounds like an elegant solution this problem.
