### ISSUE TITLE
add transformer strategy that parses from block-logs transformation to NFT ID (compatible with web3subgraph)

### ISSUE THREAD

**Issue by TimDaub** [neume-network/strategies#215]
- see this snippet https://github.com/neume-network/strategies/blob/3b0480d9c5e0a39e3f87cea410fc19207f788794/src/strategies/call-block-logs/transformer.mjs#L77
- make it a separate strategy
- blocked by #177

**Comment by TimDaub** [comment]
Actually, since this implementation is blocked by #177, the more sensible option would be to adjust all strategies taking data from web3subgraph-transformation and making them compatible with the outputs of call-block-logs-transformation

**Comment by il3ven** [comment]
Can I work on this? We need the output call-block-logs-transformer to be similar to web3subgraph-transformer. So other strategies can consume it without requiring any modifications. Right?

**Comment by TimDaub** [comment]
> We need the output call-block-logs-transformer to be similar to web3subgraph-transformer.

yeah that's one option and probably the simplest solution

**Comment by il3ven** [comment]
> yeah that's one option

I am open to other options too. What are they? Refactoring all the strategies to directly consume call-block-logs and making them loosely coupled? As of now I can't think of ways to loosely couple existing strategies.

**Comment by TimDaub** [comment]
> As of now I can't think of ways to loosely couple existing strategies.

same. And so I think creating an output from call-block-logs-transformation that mimics web3subgraph-transformation is for now the best solution.

Generally though, but this is meant more for the longer term, we probably want each strategy to somehow type-define a data structure schema. E.g. that call-soundxyz-tokenURI expects the schema of web3subgraph-transformation and through that we could have at least some verification at runtime if the result is gonna be valid or not. But I'm not sure that's even the best way, because I don't see how that'd make the coupling loose. Probably better would be where a strategy is fed a certain input. Dunno. Anyways, for now creating a web3subgraph-transformation is good! Go for it!

**Comment by TimDaub** [comment]
btw since you're probably gonna interact with the contract addresses and their name, this issue can also be interesting:

- https://github.com/neume-network/strategies/issues/219
