### ISSUE TITLE
update @neume-network/schema once neume-network/schema#31 has been released

### ISSUE THREAD

**Issue by il3ven** [neume-network/strategies#223]
Merging PR #222 for now but not updating @neume-network/schema package version as I can't release. (neume-network/schema#31)

**Comment by TimDaub** [comment]
https://github.com/neume-network/schema/blob/main/changelog.md#051

**Comment by il3ven** [comment]
Fixed in 3df5ed2179351fab2e7e2f5222d439d713d6bfc8
