### ISSUE TITLE
some call-block-logs-extraction calls don't resolve in downloaded logs

### ISSUE THREAD

**Issue by TimDaub** [neume-network/strategies#228]
```
{
  type: 'json-rpc',
  commissioner: 'call-block-logs',
  method: 'eth_getLogs',
  params: [ { fromBlock: '0xe5a709', toBlock: '0xe5a709' } ],
  version: '0.0.1',
  options: { url: 'http://127.0.0.1:8545', signal: {} },
  results: [],
  error: null
}
```

- see this response from our erigon node.
- https://etherscan.io/block/15403917, but this block contains transactions that emit logs, e.g. this one: https://etherscan.io/tx/0x2e7ade86e34bb40d6c85c8c26c67525c7a2515dddfa7b4647fd384bd44aec966
- So why was it returned empty from extraction worker?

**Comment by il3ven** [comment]
Hijacking this issue to report that locally with node.rugpullindex.com I am getting an empty result i.e. `[]`. I don't get an empty result if I change my RPC endpoint. node.rugpullindex.com also works if I get_Logs for an older block but for recent blocks such as `0xeaa78d` it doesn't.

**Comment by TimDaub** [comment]
Thanks for the information, this is starting to sound a bit like an Erigon bug. But I'd like to be sure that e.g. the extraction worker isn't at fault here. E.g. I was wondering if there is a bug where a connection timeout results in results: []

**Comment by il3ven** [comment]
It definitely is an Erigon bug.

This incorrectly returns `0xe5a51a`.
```
curl -X POST \
  -H "Authorization: Bearer <token>" \
  -H "Content-Type: application/json" \
  --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' \
  https://node.rugpullindex.com/
```

**Comment by TimDaub** [comment]
> It definitely is an Erigon bug.
> 
> This incorrectly returns `0xe5a51a`.
> 
> ```
> curl -X POST \
>   -H "Authorization: Bearer <token>" \
>   -H "Content-Type: application/json" \
>   --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' \
>   https://node.rugpullindex.com/
> ```

great find, what I also find interesting is this:

```
root@ethnode ~ # curl -s -X POST  -H "Content-Type: application/json"   --data '{"jsonrpc": "2.0","method": "eth_blockNumber","params": [],"id": 0}'   http://localhost:8545
{"jsonrpc":"2.0","id":0,"result":"0xe5a51a"}
root@ethnode ~ # curl -s -X POST  -H "Content-Type: application/json"   --data '{"jsonrpc": "2.0","method": "eth_syncing","params": [],"id": 0}'   http://localhost:8545
{"jsonrpc":"2.0","id":0,"result":false}
```

so this is clearly a problem with the erigon instance. I'll attempt to fix.

**Comment by TimDaub** [comment]
Bug report on Erigon tracker: https://github.com/ledgerwatch/erigon/issues/5184

**Comment by TimDaub** [comment]
In fact, confusingly the Ethereum APIs seem to be this way: https://github.com/ethereum/execution-apis/issues/296

**Comment by TimDaub** [comment]
resolved as an issue of rugpullindex erigon node.
