### ISSUE TITLE
we should allow calling a transformer with a specific file name

### ISSUE THREAD

**Issue by TimDaub** [neume-network/strategies#241]
e.g. logs-to-subgraph actually needs to transform call-block-logs-transformation but it implicitly expects logs-to-subgraph-extraction

**Comment by il3ven** [comment]
Doesn't https://github.com/neume-network/strategies/pull/222 solve this issue? We can pass file name as the first argument.

**Comment by TimDaub** [comment]
ah so the first argument of `transformer` in the crawl path is the data source. Awesome! Yeah then it's solved, I must have missed this!
