### ISSUE TITLE
Implement Noizd transformer

### ISSUE THREAD

**Issue by TimDaub** [neume-network/strategies#25]
## Scope

- we need a strategy to handle https://noizd.com/ metadata extraction and transformation. For this issue, we want to exclusively focus on implementing a noizd data extractor and transformer.
- For a NOIZNFT at [this contract](https://etherscan.io/address/0xf5819e27b9bad9f97c177bf007c1f96f26d91ca6#readContract), (we used tokenId:0), it returns  ipfs://QmUkHiRMC2wvNWef6Z1Lx522JPcLx2sBmavsPgbLVsPpxH which in turn returns the following JSON

```json
{"contract":"0xF5819E27B9bAD9F97c177Bf007c1F96F26D91CA6","image":"https://cf-prod.noizd.com/e060c2ae-5211-4617-a25b-6278e485d818/68c91b9a-d83c-427d-bf95-509ec46640a2.png","audio_url":"https://cf-prod.noizd.com/e060c2ae-5211-4617-a25b-6278e485d818/a63ac588-b3c0-400a-8909-ed2ec884d820.mpeg","animation_url":"https://cf-prod.noizd.com/e060c2ae-5211-4617-a25b-6278e485d818/a63ac588-b3c0-400a-8909-ed2ec884d820.mpeg","external_url":"https://www-prod.noizd.com/assets/8cc035fa-5aca-406f-be34-6ebd8389e26b","name":"Rick and Morty","description":"You know I keep it wavey with that champion sound 🎶 🎧","artist_name":" ","artist_address":"0xE7c8566EB4e7d8310d415d73730d665f2bEcFD14","artist_link":"https://www-prod.noizd.com/user/e060c2ae-5211-4617-a25b-6278e485d818","attributes":[{"trait_type":"genres","value":"Instrumental, Hip Hop Instrumental"},{"trait_type":"languages","value":""},{"trait_type":"countries","value":"BW"},{"trait_type":"preview","value":"https://cf-prod.noizd.com/e060c2ae-5211-4617-a25b-6278e485d818/a63ac588-b3c0-400a-8909-ed2ec884d820.mpeg"}]}
```

- we accumulate all noizd minting event logs here: https://github.com/neume-network/data/blob/main/results/logs-to-subgraph-transformation so they can be used similar to how e.g. soundxyz strategies do it using a line reader

**Comment by Kunkka0822** [comment]
Assigned to Raika

**Comment by neatonk** [comment]
Commenting in response to questions from Raika in Discord...

I think you just need to add two files:
- `src/strategies/noizd-get-tokenuri/extractor.mjs`
- `src/strategies/noizd-get-tokenuri/transformer.mjs`

These would be similar to the soundxyz-get-token-uri extractor and transformer.

**Comment by Kunkka0822** [comment]
@neatonk @TimDaub 

Do I have to get metadata from tokenURI, but not tokenURI from smart contract for this issue?

**Comment by il3ven** [comment]
I think we will also need:
- `src/strategies/noizd-call-tokenuri/extractor.mjs`
  This will get the tokenUri given a tokenId. We will get the tokenId by reading the `logs-to-subgraph` strategy. The `logs-to-subgraph` strategy already has valid tokenIds of Noizd NFTs.

- `src/strategies/noizd-call-tokenuri/transformer.mjs`
  The tokenUri returned from the extractor will be encoded. This transformer will decode it to finally get `ipfs://QmUkHiRMC2wvNWef6Z1Lx522JPcLx2sBmavsPgbLVsPpxH` for tokenId=0.

Again, they will be like `soundxyz-call-tokenuri`.

Once we have the tokenUri we can implement noizd-get-tokenuri to get the content of the URI. In our example that would be.
```
{"contract":"0xF5819E27B9bAD9F97c177Bf007c1F96F26D91CA6","image":"https://cf-prod.noizd.com/e060c2ae-5211-4617-a25b-6278e485d818/68c91b9a-d83c-427d-bf95-509ec46640a2.png","audio_url":"https://cf-prod.noizd.com/e060c2ae-5211-4617-a25b-6278e485d818/a63ac588-b3c0-400a-8909-ed2ec884d820.mpeg","animation_url":"https://cf-prod.noizd.com/e060c2ae-5211-4617-a25b-6278e485d818/a63ac588-b3c0-400a-8909-ed2ec884d820.mpeg","external_url":"https://www-prod.noizd.com/assets/8cc035fa-5aca-406f-be34-6ebd8389e26b","name":"Rick and Morty","description":"You know I keep it wavey with that champion sound 🎶 🎧","artist_name":" ","artist_address":"0xE7c8566EB4e7d8310d415d73730d665f2bEcFD14","artist_link":"https://www-prod.noizd.com/user/e060c2ae-5211-4617-a25b-6278e485d818","attributes":[{"trait_type":"genres","value":"Instrumental, Hip Hop Instrumental"},{"trait_type":"languages","value":""},{"trait_type":"countries","value":"BW"},{"trait_type":"preview","value":"https://cf-prod.noizd.com/e060c2ae-5211-4617-a25b-6278e485d818/a63ac588-b3c0-400a-8909-ed2ec884d820.mpeg"}]}
```
