### ISSUE TITLE
soundxyz-call-tokenuri-transformation must not automatically fail if soundxyz-call-tokkenuri-extraction didn't commit a file

### ISSUE THREAD

**Issue by TimDaub** [neume-network/strategies#251]
- as is e.g. true in this case: https://github.com/neume-network/data/runs/8120475676?check_suite_focus=true#step:3:331

**Comment by il3ven** [comment]
Is the solution here to check if a file exists before reading from it like in https://github.com/neume-network/strategies/commit/66814308e36af10bb626877ab715399ede31b3ce? Or are you expecting some other solution?
