### ISSUE TITLE
strategy-factories › get-ipfs-tokenuri › extractor_test › get-ipfs-tokenuri extractor is timing out in CI

### ISSUE THREAD

**Issue by TimDaub** [neume-network/strategies#264]
- https://github.com/neume-network/strategies/runs/8210904481?check_suite_focus=true
- it doesn't happen on my local machine so I wonder if it is a configuration or network issue

**Comment by TimDaub** [comment]
@il3ven as you're the author of this test

**Comment by il3ven** [comment]
Closing as duplicate of #280
