### ISSUE TITLE
Make tests easier to run

### ISSUE THREAD

**Issue by neatonk** [neume-network/strategies#276]
I ran into a few hiccups while trying to run the tests in this repository and wanted to document them here with suggested improvements.

- A section on tests should be added to the README with setup instructions and caveats.
- Explain `.env` file setup. I used `RPC_HHTP_HOST=https://rpc.ankr.com/eth` and `IPFS_HTTPS_GATEWAY=https://cloudflare-ipfs.com/ipfs/` (no api key needed).
- Add empty `data` directory to repo and hide it's contents or ask user to create it. It wasn't clear until I looked at the .gitignore file that the `data` directory should be a temp directory in this repo. Also not sure if it needs to be cleaned up between test runs or if that is handled.
- Tests seem a bit brittle wrt ethereum network state. One tests for soundxyz is failing for me due soundxyz metadata changes.

**Comment by TimDaub** [comment]
> * Tests seem a bit brittle wrt ethereum network state. One tests for soundxyz is failing for me due soundxyz metadata changes.

should have been solved in 94eff659eb879d3c4b3be8f90cedb31b4b2af94e

**Comment by TimDaub** [comment]
> * Tests seem a bit brittle wrt ethereum network state. One tests for soundxyz is failing for me due soundxyz metadata changes.

just found another one: https://github.com/neume-network/strategies/issues/280

**Comment by il3ven** [comment]
> It wasn't clear until I looked at the .gitignore file that the data directory should be a temp directory in this repo

This must be something specific to your system. I don't have a data directory and the tests do pass. Similarly, our CI also doesn't create a data directory. However it does add the [`DATA_DIR`](https://github.com/neume-network/strategies/blob/main/.github/workflows/node.js.yml#L34) environment variable.

**Comment by neatonk** [comment]
> This must be something specific to your system. I don't have a data directory and the tests do pass. Similarly, our CI also doesn't create a data directory. However it does add the [`DATA_DIR`](https://github.com/neume-network/strategies/blob/main/.github/workflows/node.js.yml#L34) environment variable.

Thanks for that. It looks like the `DATA` var is probably not used when running tests. In which, case it should be removed from the example env or commented to explain that it is not used.

**Comment by neatonk** [comment]
I can put together a PR with these changes at a later date. Just wanted to document and clarify this stuff before I get too familiar with the code.

**Comment by TimDaub** [comment]
> > This must be something specific to your system. I don't have a data directory and the tests do pass. Similarly, our CI also doesn't create a data directory. However it does add the [`DATA_DIR`](https://github.com/neume-network/strategies/blob/main/.github/workflows/node.js.yml#L34) environment variable.
> 
> Thanks for that. It looks like the `DATA` var is probably not used when running tests. In which, case it should be removed from the example env or commented to explain that it is not used.

I made some edits to .env-copy today and I now recommend to soft link the .env file from core

**Comment by TimDaub** [comment]
new section: https://github.com/neume-network/strategies#installation-and-contributing

**Comment by TimDaub** [comment]
IMO we should close this issue as all problems should be addresse now, or what's left?

**Comment by neatonk** [comment]
Agreed

> IMO we should close this issue as all problems should be addresse now, or what's left?
