### ISSUE TITLE
Implement call-soundeditionv1-tokenuri extractor and transformer

### ISSUE THREAD

**Issue by Kunkka0822** [neume-network/strategies#311]
- We need a `call-soundeditionv1-tokenuri` strategy to get the  `tokenUri`. The result is something like `ar://zUTuV0VL7w1z5cuGkBs2b-O3DRY2O2qA_ifSQqjLnzA/1`.

- We can get tokenUri from the sound edition contracts we found in #295. We should track Transfer events where tokenId is 1. 
- You can find detail information on #294

**Comment by Kunkka0822** [comment]
#294

**Comment by il3ven** [comment]
From what I understood in the #294 discussion. We should track all tokenIDs and not only tokenID=1. From the tokenURI we can get `trackNumber`. It will let us filter all the unique songs. If two tokenIDs have the same trackNumber then they are the same song.

Please correct me if I am wrong.

**Comment by Kunkka0822** [comment]
> > From what I understood in the #294 discussion. We should track all tokenIDs and not only tokenID=1. From the tokenURI we can get `trackNumber`. It will let us filter all the unique songs. If two tokenIDs have the same trackNumber then they are the same song.
> > Please correct me if I am wrong.
> 
> yes all tokenURIs

Okay, I got it.
I will work on this issue.

**Comment by TimDaub** [comment]
@Kunkka0822 is there a reason why this is a pinned issue?

**Comment by TimDaub** [comment]
> * We need a `call-soundeditionv1-tokenuri` strategy to get the  `tokenUri`. The result is something like `ar://zUTuV0VL7w1z5cuGkBs2b-O3DRY2O2qA_ifSQqjLnzA/1`.

this is now done.

**Comment by TimDaub** [comment]
@Kunkka0822 the next step is taking all the called tokenURIs (which are Arweave links) and then sending type: arweave messages to the extraction-worker to download all the JSON objects.

**Comment by Kunkka0822** [comment]
@TimDaub Okay, I got it. So the next step will be sound-protocol-get-tokenuri.
May I implement feature to filter unique songs by `tracknumber` in this part or not?

**Comment by TimDaub** [comment]
We definitely want that at some point but I'd leave it to your disgression where you think it fits best to implement it

**Comment by Kunkka0822** [comment]
@TimDaub I think this issue is already solved.
