### ISSUE TITLE
Implement Catalog v1 extractor

### ISSUE THREAD

**Issue by reimertz** [neume-network/strategies#33]
## Scope

- Among other things, we currently don't have access to Catalog audio files due to https://github.com/neume-network/strategies/blob/main/src/strategies/catalog/transformer.mjs#L40
- Catalog (or rather Zora) isn't compliant to EIP-721. `tokenURI` returns the media blob, and `tokenMetadataURI` returns the token's metadata JSON

## Deliverables

- Implement an extractor for catalog v1
- In catalogv1's transformer strategy, create a matching manifestation for the audio track: https://github.com/neume-network/strategies/blob/27cb5d708deab2e02fc4c4b0bd97d538406a5037/src/strategies/catalog/transformer.mjs#L41

**Bounty**: Yes

**Comment by TimDaub** [comment]
removed bounty: yes. This needs prior architecture work.
