### ISSUE TITLE
sound-protocol-get-tokenuri hard codes arweave gateway uri

### ISSUE THREAD

**Issue by TimDaub** [neume-network/strategies#336]
- https://github.com/neume-network/strategies/blob/57e4f2cf92f28307e7ed6d6a2c9d7ab810c82bf4/src/strategies/sound-protocol-get-tokenuri/extractor.mjs#L50
- this should be part of the configurations e.g. in the env file and then propagated through /core (like we do with IPFS etc.)

/cc @Kunkka0822

**Comment by Kunkka0822** [comment]
@TimDaub Do I have to add this value to /core project too?
https://github.com/neume-network/core/blob/1cd0595ee009dc109c00855966407561686193cc/package.json#L62-L69
