### ISSUE TITLE
Create new strategy for Catalog custom 721 contract

### ISSUE THREAD

**Issue by reimertz** [neume-network/strategies#34]
Catalog created and migrated to their own [custom 721 contract](https://etherscan.io/token/0x23581767a106ae21c074b2276d25e5c3e136a68b) on April 9th. 

Tracks are being created by this contract: https://etherscan.io/address/0x0bC2A24ce568DAd89691116d5B34DEB6C203F342#readProxyContract

**Bounty**

Yes

**Comment by TimDaub** [comment]
@il3ven @sirnicolaz interested in taking this one over? Should now work with call-block-logs strategy

**Comment by TimDaub** [comment]
implemented in /strategies. Only integration that is left to do is adding it to the crawler steps of neume-network/data
