### ISSUE TITLE
explicitly require strategy name as exportable module var in interface definition

### ISSUE THREAD

**Issue by TimDaub** [neume-network/strategies#41]
- When testing all extractor strategies interface compliance in this test: https://github.com/neume-network/strategies/blob/6321b83e4cc1ddb1b2551f1137e103fae356fb33/test/disc_test.mjs#L29, we now also want to make sure that a `name: String` property is always exported.
- An example of a compliant strategy is: https://github.com/neume-network/strategies/blob/6321b83e4cc1ddb1b2551f1137e103fae356fb33/src/strategies/web3subgraph/extractor.mjs#L3
- If you end up working on this task, make sure also to update the readme.md's interface definition here: https://github.com/neume-network/strategies#extractor-strategy-interface-definition

**Comment by il3ven** [comment]
This issue can be closed as this test checks for strategy name.

https://github.com/neume-network/strategies/blob/05da9c363ff9786c3d6f6bb47c037e9e8eb35920/test/strategy_name_test.mjs#L16
