### ISSUE TITLE
consider deprecating state in extractor lifecycle components

### ISSUE THREAD

**Issue by TimDaub** [neume-network/strategies#46]
- context is this discussion: https://github.com/neume-network/strategies/commit/6321b83e4cc1ddb1b2551f1137e103fae356fb33#r74319979
- this issue is probably best suited for @il3ven or me

**Comment by il3ven** [comment]
If I am correct you have deprecated state in favour of args? So, whatever is in message.args will be passed to init or update functions.

**Comment by TimDaub** [comment]
correct
