### ISSUE TITLE
Propose an alternative architecture

### ISSUE THREAD

**Issue by il3ven** [neume-network/strategies#49]
### Problem

Currently, our strategies return messages which control the flow of the application. There are many conventions which are not immediately clear when looking at the code. Hence, making the flow a little difficult to understand. The following are few conventions provided as example.

- `init` function will be called when the message.type is extraction.
    ```js
    {
        type: "extraction",
        version: "0.0.1",
        name: "soundxyz",
        state: { tokenId },
        results: null,
        error: null,
    }
    ```
- a message with type other than _extraction_ or _transformation_ is sent to extraction_worker
- a response from the extraction_worker is handled by the update function 

We also face problems like the one being discussed [here](https://github.com/neume-network/strategies/commit/6321b83e4cc1ddb1b2551f1137e103fae356fb33#r74406854). In this problem, we need to determine if there are no more `update` calls.

### Proposal

We write our code using async/await but still use extraction_worker.

```js
function generate(first, lastId) {
  return {
    type: "graphql",
    commissioner: name,
    version,
    options: {
      url: "https://api.thegraph.com/subgraphs/name/timdaub/web3musicsubgraph",
      body: JSON.stringify({
        query: `
            query manyNFTs($lastId: String) {
              nfts(first: ${first}, where: { id_gt: $lastId }) {
                id
              }
            }`,
        variables: { lastId },
      }),
    },
    results: null,
    error: null,
  };
}

async function web3subgraph() {
  const props = {
    autoStart: true,
    first: 1000,
    lastId: "",
  };

  let lastId = "";
  let nfts = [];

  // send is the async/await version of worker.postMessage
  // we send the message to extraction_worker and wait for the response
  do {
    const message = generate(props.first, lastId);
    const { results: {data} } = await send(message);
    nfts = data.nfts
    if (nfts.length) {
      lastId = nfts[nfts.length - 1].id;
    }
    write('web3subgraph-extraction', nfts) // Instead of relying on convention we can use explicit file name
  } while (nfts.length != 0);

  // transformer is same as before but now we are explicitly calling it
  // hence making the flow more clear
  return write('web3subgraph-transformer', await lineReader(filePath, transformer));
}
```

#### More benefits

- Maintaining state is easier. State is just a variable defined inside the function.
  ```js
  async function web3subgraph() {
    const state = {}

    state = {...state, result: await send({}) }
  }
  ```
- We can perform some computation when extraction is over. Kind of like onUnmount.
  ```js
  async function web3subgraph() {
    const message = generate(props.first, lastId);

    await Promise.all(
      new Array(25)
        .fill(0)
        .map((_, i) => {
          const data = encodeCallSignature(
            props.signatures.tokenURI,
            ["uint256"],
            [i+1]
          );

          return send({
            type: "json-rpc",
            method: "eth_call",
            params: [
              {
                from,
                to: props.contract.address,
                data,
              },
              "latest",
            ],
          });
        })
        .then(write) // write to file when response is received from the worker
    );

    // now all the json-rpc calls have been made and data has been written
    // we can call the transformer
  }
  ```

#### How to implement `send`?

Check [this](https://gist.github.com/bellbind/7b412e07a746ea42b9cfa840fd535557) GitHub gist. I did try it with our extraction_worker and it works.

### Conclusion

By using the above approach we simplify the strategies but keep the benefits provided by extraction_worker. 

I am happy to clarify any doubts and also happy to be corrected.

**Comment by il3ven** [comment]
@TimDaub If you find time please have a look at this. If we are to move with the proposed architecture then it doesn't make sense for me to solve other issues as the code I write for them will need to be changed.

**Comment by TimDaub** [comment]
While I appreciate your work on improving the interface, our most important goal is to ship a first version of the crawler that actually works for users like music-os. We can kewp this issue open, but I'm not interested in refactoring interfaces if it isn't for improving/enabling functionality.

**Comment by il3ven** [comment]
The utility behind refactoring is that implementing strategies will be faster and easier. Problems like #45 will be easily solvable. 

I find the current architecture a little confusing and difficult to develop to. Maybe I will master it after solving a few issues but the above architecture makes perfect sense to me. I strongly believe we should develop using the above approach.

**Comment by TimDaub** [comment]
The problem outlined above is non acceptable as a problem statement outline - it contains too much technical vision.

I don't doubt you genuine having a problem understanding. But what can help understanding the "convention littered" code? E.g. a simplest possible thing would be to add docs.

So e.g. a valid issue would be: "It's unclear that to write, a string has to be passed in return" and then we'd talk about solutions.

Closing this now as it contains too much technical vision.

**Comment by TimDaub** [comment]
More thoughts:

> Check [this](https://gist.github.com/bellbind/7b412e07a746ea42b9cfa840fd535557) GitHub gist. I did try it with our extraction_worker and it works.

I'm doubting that using `once` really works and I'd prefer to now use it. The problem it has is that for each send it'd start a new event listener to an external program. Nodejs limits event listeners to just a handful (e.g. it starts warning when you have more than 10 or so) - they can cause memory leaks. Hence, it's important we'd funnel all "send"s through just one message channel and not re-open a new one everytime a user calls.

**Comment by il3ven** [comment]
> I'm doubting that using once really works and I'd prefer to now use it.

The [node.js documentation](https://nodejs.org/api/events.html#eventsdefaultmaxlisteners) says that by default there can be at max 10 event listener for the same event. Here, I think we are not adding listener on the same event. To test this I created a small program and using `send` awaited on 1 million events. The code worked without any errors or warnings. 

However, I transformed the same program to use a single event listener and found the code to run 16x faster. For now, this can be another reason to not use my proposed architecture.

I do like the above mentioned async/await approach and can even argue that we don't need extraction-worker. Workers are useful for CPU intensive tasks and not I/O bound tasks. This is an opinion I do not strongly hold because they are some other benefits too with using extraction-worker like separation of concern.

Anyway, thank you for entertaining the proposal.

**Comment by TimDaub** [comment]
> I do like the above mentioned async/await approach and can even argue that we don't need extraction-worker

I'd favor async/await over events too. But I don't know a pattern that can efficiently translate from events to async/await. Otherwise, I probably would have used it.

However, since we're essentially going to build a distributed system with neume-network, I think it can make sense seeing all inter process communication as request/response events.

> Workers are useful for CPU intensive tasks and not I/O bound tasks.

Fair criticism. But I do think we should further build an architecture where we can horizontally scale processing. E.g. today's extraction-worker may become an ETL worker one day that e.g. can also do CPU intensive tasks.
