### ISSUE TITLE
CI isn't failing when `console.log` is used.

### ISSUE THREAD

**Issue by TimDaub** [neume-network/strategies#60]
- Within the strategies repo, anyone should only ever use the specific logger: https://github.com/neume-network/strategies/blob/main/src/logger.mjs and not console.log
- `console.log` should make the CI fail

**Comment by il3ven** [comment]
I can setup ESLint for this and run it in CI. This [rule](https://eslint.org/docs/rules/no-console) will prevent console statements in the code. Should I create a PR? Do you have a different approach in mind?

**Comment by TimDaub** [comment]
sounds good, I'll assign you
