### ISSUE TITLE
When writing strategy outputs, `JSON.stringify' doesn't canonically serialize JSON objects (e.g. it assumes the order of keys in the literal). For testing snapshot writes, this can become a problem. Replace JSON.stringify with a canonical serializer

### ISSUE THREAD

**Issue by TimDaub** [neume-network/strategies#91]
e.g. here we're expecting `contract` to be before `tokenId` but JSON.stringify doesn't give this guarantee: https://github.com/neume-network/strategies/pull/89/files#diff-ec78f60b2e3856e9752c2bdbdcd1a1fe7658f9965ee49894704f83d64b9875eeR4

**Comment by il3ven** [comment]
In my opinion this won't be a problem. In case of soundxyz if we don't change the order in [`strategiess/soundxyz/extractor`](https://github.com/neume-network/strategies/blob/a330a5727721cc2820ac09a6fb1a7d2c1953c876/src/strategies/soundxyz/extractor.mjs#L78) the tests won't fail.

I maybe wrong. We can keep this issue open and solve it if we encounter the problem.

A reason for not implementing this is that it will make our application 4x slower. For source check [this](https://github.com/mirkokiefer/canonical-json#performance-comparison).

**Comment by TimDaub** [comment]
fair enough, looks like a good minimal solution
