### ISSUE TITLE
CI failing because cloudflare-eth not allowing to go back further than 128 blocks

### ISSUE THREAD

**Issue by il3ven** [neume-network/strategies#92]
In PR #77 we introduced tests for extractor strategies. In that PR we were using cloudflare-eth to query the blockchain. However, since PR #90 cloudflare-eth does not work. This is because cloudflare-eth only allows us to query the latest 128 blocks.

To make the tests pass in CI we need to use an alternative ethereum node. If that node is a paid then we will have to set the `RPC_API_KEY` environment variable before running the tests. We can do this by setting `RPC_API_KEY` as a github secret and pass the secret to ava.

The person solving this issue can assume that the secret is already present.

**Comment by TimDaub** [comment]
Assigning this to me for now as I have to add the API key to GitHub.

**Comment by TimDaub** [comment]
`${{ secrets.RPC_API_KEY}}` should now be available for node.rugpullindex.com in GH Action workflows
